language: java

addons:
  sonarcloud:
    organization: "danielemariano"
    token:
      secure: "7qYPR1ndIH4E9wD+2YH9KNb6flLiw2CnIebx/QZO/dSTNUCSFfSAMktrVCwCoR4n2wgxO7rNg5b5xLie0usM5I4Qi0aRiYDfjDybEJhawIz9E21UvV1luEchHsL1We7JC+cS1ro7Rd9K12WplMBHvU+XIkeRda0tTvA488zhcpscKkMcS3VLMmHw5FWI8TEeu6ph46xDeH7Gjg3rBfOGyvlX4RaW+Dq13MTlngklfl6bXZD6uaP7ca4oR8GAGVDXFd4vZozGljMXAS2MNJ0IUnFhq/U+Rv1wZZ0+7OOccse/A0wRyGzXfCVfl7kDk1s/lKlL1hDUA262BegvDg0boCJkRhYTBFPy9k7XfF2JdluU150SDSDMlHpy9++mA2uMt07txyKzDNHC0E7oc0cOD/nBldGrl16n7+3GxEoACioWzn4tDjegKV2PsAzVWfuKXaPRA3ZH88NuZ/vGSoUVI3EG1DHGQDNPtRMm890qG0/Epk/Lf1oraNTWX9S7n220Fkl1Amfru5GEiOan/7SZMaxUMk808mQTG+kYeHpXaYfeUD3RK8w1NrGq1Y2ozO1eF4Ci5YvVmqF6MrvAOi9I/iorrcFEa+G4qP+O/MCVcttmDMqhUtQobMLXqg09SBG9ml0JFr9WziKicsE0NhrPww76spMQicoQ25CtGi6coGc="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=danielemariano_bookkeeper-test
