language: java

addons:
  sonarcloud:
    organization: "danielemariano"
    token:
      secure: "Bj8OrowhX3UR7rA1t7/5aLcV+MaV/n0TeYdb5Hd3YwufMZ5+QWzmD3MjgVW3gEiWhYhBXhImNKURIAb9ibDCYHPECypvLQOujXHnI5eRNGUv1qLK/KoNbUkuxXoTeKTUtWZwuVtujcRwt+o6r5Y9n3+khdw+ux9LVvddUkHW3H9Am7w0hBxg2qFzTIZP51VCzNxbdaZlFLgUBIxc3IFY8A4/HYvEQ0nHWkWEIlBjLXsMHEJThkE75K6AgIqzrRAHm8kqob1bIn4Bjo0V/iDM5zJKnAeOrLpEGdCOf7J5cryRV1LzDskhXQ4GkiJNA19RO7C/iInu3dUxVVTeTuMX53rb7PCDmHRT/kkI5XUTG+8MXeQEv1Y3PMVQ23olSBKLfDLuBlkXshpLgdB6EwAGsZqhOGzqpVvrmQuNQPwaJpewSg/y99ICErDyDVnVTd3PFGWlUvrYBo7HajZewgKyX2T4WIJxP6FtcldoX+Wgiqzkj/7HzsZnG1r68xvv8bezCWTjaOkZrYnoe01mXN4KR8urQB9oHy1Gr16ufYSlYPLJpEn8DG1HtRXRfOlZ1NDFUB/m9W+YZCoJAE+B5NAh5OqMwXMFi+G0dFZ/Ac2cwcLXXAiSCqm5GVMbtcMI1Ym2e+XM71mdtH3/2J0P/gNh3VtzI6CPe4JGmnqHRChZRoM="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  # - sonar-scanner
  # - sonar-scanner
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=danielemariano_bookkeeper-test
