language: java

addons:
  sonarcloud:
    organization: "danielemariano"
    token:
      secure: "Ni6ppeqwv8XK81F02HdgjzghHz4QH3VisFNatxjlhytzQUz9a8A88c8TF6+KKSa6Y+2+xTqdcfT8TL3dFlRrwGLRDLQJ2d6x1AqgnwW//hIOl6SJpjyo5Yi+Jia00m1cXC9G2GPh0RYLh14d1p1GDiiZUpS5dHRqFKEvdGQVKl+ELQTKUg8J6d3KcCJsjPk3KclnvPQKHTK/inDNChqormPEdlwQipVjjHka2OOKSwgeP8xCt9NljgpPyQwXlLI87xsjMUFF7phpAx6QPQs2iFNxTqOQLTHoQFjKiiX0XlK5FvoIRlrEKjkniH2p4yFUjSxWKRlk/BhHxJKdKxBMrBbm2+/eG++jl4w+6H2wIqTAUuYYHCjb0i4IPYIHwM5Js6E1vT2Sy/D2+hD9MNq9Ho2nPv9OV/2HLU555MMpvtPaUKvSxcGuKv4kpmOWwE64b6hGpnvpKDFb7A16S/0N8VhQSMlGa1lh20plk1f9JSvXZc5bs0OnZU/0kqYg+xo9CY2W59iktr5dB+u0lMTE52618ILwhr3ooUpWRWp8jjmjXzzS6pyPKvdVAutlC3PFvJp9LVxBNXUEgCkT1hy3hjEBHPu5FtYorBMqbTztKWFREEEP8EVktLOarlILBUk8mMmwRiTLXXu3rQOaM8CoOX1P/NCKAx+NbiWPNB623HY="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=danielemariano_bookkeeper-test
